name: GitHub CLI PPTX verification

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: cli/gh-actions@v2
      - name: Check GitHub CLI
        run: gh --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate and verify PPTX
        run: python verify_pptx.py
